@startuml

class Agv {
    -Container: container
    -Status: status
    +Agv()
}
class Anchorage extends ShipPlaces {
    -ShipQueue: Queue<Ship>
    +Anchorage(Name: string,Spaces: int, Type: Shiptype)
    -MoveShipFromQueue(): Ship
    -AddShipToQueue(ship: Ship): void
    -ReturnAllShips() : List<Ship>
    -AvalibleSpace : bool
}
class Column{
    -contianerspace : Containerspace
    -StackedContainers : Collection<Stack<Container>>
    +AmountContainers : int
    -MaxContainers: int
    -MaxHeight : int
    -Type : ContainerType

    -Column(width : int, height: int)
    -AddContainer(container: Container) : void
    -InitializeContainerType(container: Container) : void
    -IsContainerLongOverdue(current : Datetime) : bool
    -RetrieveOverdueContainer(current : Datetime): Container
}
class ContainerSpace {
    -StorageColumns : Collection<StorageColumns>
    +AGVs : Collection<AGV>
    -TruckPickupPercentage : double
    -DaysInStorageLimit : int

    +ContainerSpace(numberOfAGVs : int, daysInStorageLimit: int, truckPickupPercentage: double)
    +AddStorageColumn(amount:int, numberOfCranes: int,  length:int, width:int, height:int):void
    +OverdueContainers(currentDate : DateTime) : void
}
class Dockspace extends ShipPlaces {
    +Dockspace(Name: string, Spaces: int, Type: ShipType)
}
abstract class ShipPlaces {
    {static} -Next: int
    -Id: int
    +Name: string
    +Spaces: int
    +Type : ShipType
    -Ships: List<Ship>
    -Finished: List<Ship>
    +DepartingHarbour: EventHandler<DepartingHarbourArgs>

    +ShipPlaces(spaces : int, name : string, type : ShipType)
    +AddShip(ship: Ship): void
    -MoveShip(id: int): Ship
    -ReturnRepeatingShips(): List<Ship>
    -ReturnAllShips(): List<Ship>
    -AvailableSpace(): bool
    -RaiseDepartingHarbour(ship:Ship):void
}

class StorageColumn{
    -Columns: Collection<Column>
    +NumberOfCranes: int

    + StorageColumn(numberOfCranes:int, numberOfColumns: int, width: int)
}
class Unloadingspace extends ShipPlaces {
    -Cranes: int
    +TruckPickupPercentage:double
    -ContainerHistory : Collection<HistoryService>
    -TargetContainerSpace : ContainerSpace

    +Unloadingspace(Name:string, Spaces:int, Type:shipType, cranes:int, truckPickupPercentage: double, targetContainerSpace: containerSpace)
    -UnloadContainer((currentDateTime: DateTime, end: DateTime):int
    -AddShip(ship:Ship):void
}
class Container {
    {static} - Next: int
    +ID: int
    +Histories: Collection<HistoryService>
    +Type: ContainerType

    +Container(type:ContainerType)
}
class HistoryService {
    +Name: string
    +Time: DateTime
    +Description:string

    -HistoryService(name:sting, entryTime:DateTime,description:string)
    +ToString():override string
}

class Ship {
    {static} -Next:int
    +Id: int
    +ShipName: string
    +PlaceDestination: ShipPlaces
    +ArrivalTime: DateTime
    -Repeat: bool
    +status: Status
    +AmountLongContainers: int
    +AmountShortContainers: int
    +TotalContainers:int
    +Type:ShipType
    -containers: Queue<Container>
    -histories: List<HistoryService>

    +Ship(shipname:string, placeDestination:ShipPlaces,arrivaltime:DateTime,repeat:bool, amountOfShortContainers:int, amountOfLongContainers:int, type: ShipType)
    -MakeContainers(): void
    -MoveContainer(): Container
    -AddHistory(history: HistoryService): void
    -RemoveHistory(history: HistoryService): void
}

class Harbour implements IHarbour {
    -name:string
    -ShipHistory: List<HistoryService>
    -ContainerHistory: List<HistoryService>
    -ShipPlacesList: List<ShipPlaces>
    -ShipsList: List<Ship>
    -AnchorageHarbour : Anchorage
    +ArrivedToHarbour: EventHandler<ArrivedToHarbourArgs>
    +DepartingAnchorage: EventHandler<DepartingAnchorageArgs>
    +MidnightStatusUpdate: EventHandler<MidnightStatusUpdateArgs>
    +MovingToAnchorage: EventHandler<MovingToAnchorageArgs>
    +ReachedDestination: EventHandler<ReachedDestinationArgs>
    +ShipSailing: EventHandler<ShipSailingArgs>

    +Harbour(ship:List<Ship>, shipPlaces:List<ShipPlaces>,name:string, SpacesInAnchorage:int)
    +Harbour(name: string, spaceInAnchorage)
    +RemoveShip(ship: Ship): void
    +RemoveAllShip(): void
    +AddShipPlace(shipPlaces ShipPlace)
    +AddAllShipPlaces(shipPlaces: List<ShipPlaces>)
    +AddShip(ship: Ship): void
    +AddAllShips(Allships: List<Ship>): void
    +Run(Start: DateTime, end: DateTime): void
    -MoveShip(TheShip: Ship): Ship
    -AddSpecificPlace(ShipPlaceId:int, ship:Ship):void
    +AddShipToAnchorage(ship: Ship, current: DateTime): void
    +MoveShipFromAnchorage(shipPlaces: ShipPlaces, ship: Ship, current: DateTime): void
    -RaiseArrivedToHarbour(ship: Ship):void
    -RaiseDepartingAnchorage(ship: Ship):void
    -RaiseMidnightStatus(ship:Ship):void
    -RaiseMovingToAnchorage(ship:Ship):void
    -RaiseReachedDestination(ship:Ship):void
    -RaiseShipSailing(ship:Ship):void
}
interface IHarbour {
    +Run(Start: DateTime, end: DateTime): void
    +RemoveShip(Ship: ship): void
    +RemoveAllShip(): void
    +AddShipPlace(ShipPlaces shipPlace): void
    +AddAllShipPlaces(List<ShipPlaces> shipPlaces): void
    +AddShip(Ship:ship): void
    +AddAllShips(List<Ship> Allships): void
}
enum ContainerType{
    NONE,
    LONG,
    SHORT
}

enum ShipType{
    all,
    cargo,
    passanger,
    tankship
}
enum Status{
    Avalible,
    Busy,
    Finished
}


ShipType ---> Ship
Harbour "1" *--- ShipPlaces
Harbour "1" *-- Ship
ShipPlaces "1" *-- Ship
Ship "1" *-- Container
Ship "1" *-- "many" HistoryService
Container "1" *--- HistoryService
ContainerSpace ---> Unloadingspace
Agv --o ContainerSpace
Column --o StorageColumn
StorageColumn --o ContainerSpace
ContainerType -----> Container
ContainerType -->Column
Status --> Ship
Status --> Agv









@enduml